# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 837a3a97841138ea06771bad6045b3362fa7aa538cd932cee60fea87b4a5547c05d2a49407e4eda43307ebe611f5fe3e8a0e0e311f1d79bbc29b27b2cbf04a5f

test:
  secret_key_base: 149117d41b7d86cf82a89b538c0a0a64cde2d32c98f132c750330178b60bdeaa276a219ada4723b95a92363a60344272826837cb5b712aa2b7b35707ae9e5122

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
